FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:1.23.2@sha256:ca0c771ecd4f606986253f747e2773fe2960a6b5e8e7a52f6a4797b173ac7f56 AS golang

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:d342aa80781bf41c4c73485c41d8f1e2dbc40ee491633d9cafe787c361dd44ff AS builder
ARG GOLANG_VERSION=1.23.2

# Install system dependencies
RUN dnf upgrade -y && dnf install -y \
    gcc \
    make \
    openssl-devel \
    krb5-devel \
    git \
    && dnf clean all && rm -rf /var/cache/yum

# Install Go
ENV PATH=/usr/local/go/bin:$PATH

COPY --from=golang /usr/lib/golang /usr/local/go
# End of Go versioning workaround

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
#RUN go mod download

# Copy the go source
COPY . .

# Build
RUN    CGO_ENABLED=1    GOEXPERIMENT=strictfipsruntime    go build -tags strictfipsruntime -ldflags="$(LD_FLAGS)" -o bin/manager cmd/kueue/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0 AS runtime

## Build args to be used at this step
ARG USER=65532

LABEL com.redhat.component="odh-kueue-controller-container" \
      name="managed-open-data-hub/odh-kueue-controller-rhel8" \
      description="Kueue is a set of APIs and controller for job queueing. It is a job-level manager that decides when a job should be admitted to start (as in pods can be created) and when it should stop (as in active pods should be deleted)." \
      summary="odh-kueue-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-kueue-controller" \
      io.k8s.description="odh-kueue-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"


WORKDIR /
USER root
COPY --from=builder /workspace/bin/manager /manager
USER 65532:65532

ENTRYPOINT ["/manager"]
